// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: target/tmp/vector_tile.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vector_tile;

